version: "3.7"

services:
    redis:
        image: redis
        restart: on-failure
        container_name: redis
        networks:
            - rundax
        volumes:
            - redis_data:/data
        ports:
            - ${REDIS_PORT}:6379
        healthcheck:
            test: ["CMD", "bash", "-c", "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"]
            interval: 5s
            timeout: 10s
            retries: 5

    mysql:
        build:
            context: mysql
        image: mysql:5.7
        restart: on-failure
        container_name: mysql
        networks:
            - rundax
        volumes:
            - ./mysql/initdb:/docker-entrypoint-initdb.d:ro
            - mysql_data:/var/lib/mysql
            - mysql_logs:/var/log/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
networks:
    rundax:
        external: true

volumes:
    redis_data:
    mysql_data:
    mysql_logs:
